# Generated by Django 4.1.7 on 2023-03-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='added_at',
        ),
    ]
